permalink: pretty

# Setup
title: Kevin Ferri
tagline: Blog
description: Powered by Jekyll.
url: ''
baseurl: '/me'
paginate: 5

# About/contact
author:
  name: Kevin Ferri
  email: kevinferri@gmail.com

# Custom vars
version: 1.0.0

gems: [jekyll-paginate]
